"""add PeriodicTask model

Revision ID: 08168a53eb83
Revises: dce162c0888d
Create Date: 2025-12-01 14:36:41.592530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08168a53eb83'
down_revision: Union[str, None] = 'dce162c0888d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodic_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='任务名称'),
    sa.Column('task', sa.String(length=255), nullable=False, comment='任务函数路径'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('schedule_type', sa.String(length=50), nullable=False, comment='调度类型 (interval/crontab)'),
    sa.Column('schedule_value', sa.Text(), nullable=False, comment='调度参数 (JSON格式)'),
    sa.Column('args', sa.Text(), nullable=True, comment='任务参数 (JSON格式)'),
    sa.Column('kwargs', sa.Text(), nullable=True, comment='任务关键字参数 (JSON格式)'),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periodic_tasks')
    # ### end Alembic commands ###
