"""first build

Revision ID: 47acc5be400c
Revises: 
Create Date: 2024-12-31 12:03:48.170581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47acc5be400c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process', sa.String(length=128), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realname', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=320), nullable=False),
    sa.Column('is_super_user', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=128), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=False),
    sa.Column('spcType1', sa.String(length=80), nullable=False),
    sa.Column('spcType2', sa.String(length=80), nullable=True),
    sa.Column('spcType3', sa.String(length=80), nullable=True),
    sa.Column('sampleSize', sa.Integer(), nullable=False),
    sa.Column('USL', sa.Float(), nullable=False),
    sa.Column('LSL', sa.Float(), nullable=False),
    sa.Column('selectedChecks', sa.String(length=80), nullable=True),
    sa.Column('dataCollectionType', sa.String(length=80), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('samples', sa.String(length=128), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('process')
    op.drop_table('department')
    # ### end Alembic commands ###
